basePath: /
host: localhost:8080
info:
  contact: {}
  description: This is a sample API for demonstration.
  title: My Go API
  version: "1.0"
paths:
  /greet:
    get:
      consumes:
      - application/json
      description: Returns a simple greeting message
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Get a greeting
      tags:
      - greetings
swagger: "2.0"
